allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@esportsplus/typescript@0.31.0 || 0.32.0 || 0.33.0 || 0.33.2 || 0.33.4'
  - tsc-alias@1.9.4
  - '@esportsplus/utilities@0.28.1'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
