const PACKAGE_NAME = '@esportsplus/reactivity';

const COMPUTED = Symbol.for(`${PACKAGE_NAME}/computed`);

const REACTIVE_ARRAY = Symbol.for(`${PACKAGE_NAME}/reactive.array`);

const REACTIVE_OBJECT = Symbol.for(`${PACKAGE_NAME}/reactive.object`);

const SIGNAL = Symbol.for(`${PACKAGE_NAME}/signal`);

const STABILIZER_DEFERRED = 4;

const STABILIZER_IDLE = 0;

const STABILIZER_RESCHEDULE = 1;

const STABILIZER_RUNNING = 2;

const STABILIZER_SCHEDULED = 3;

const STATE_CHECK = 1 << 0;

const STATE_DIRTY = 1 << 1;

const STATE_RECOMPUTING = 1 << 2;

const STATE_IN_HEAP = 1 << 3;

const STATE_COMPUTED = 1 << 4;

const STATE_ERROR = 1 << 5;

const STATE_EFFECT = 1 << 6;

const STATE_NOTIFY_MASK = (STATE_CHECK | STATE_DIRTY);


export {
    COMPUTED,
    PACKAGE_NAME,
    REACTIVE_ARRAY, REACTIVE_OBJECT,
    SIGNAL,
    STABILIZER_DEFERRED, STABILIZER_IDLE, STABILIZER_RESCHEDULE, STABILIZER_RUNNING, STABILIZER_SCHEDULED,
    STATE_CHECK, STATE_COMPUTED, STATE_DIRTY, STATE_EFFECT, STATE_ERROR, STATE_IN_HEAP, STATE_NOTIFY_MASK, STATE_RECOMPUTING
};
