const COMPILATION_ENTRYPOINT = 'reactive';

const COMPILATION_ENTRYPOINT_REGEX = /\breactive\b/;

const COMPILATION_NAMESPACE = 'reactive';

const COMPILATION_TYPE_ARRAY = 'array';

const COMPILATION_TYPE_COMPUTED = 'computed';

const COMPILATION_TYPE_SIGNAL = 'signal';


const COMPUTED = Symbol('reactivity.computed');

const PACKAGE = '@esportsplus/reactivity';

const REACTIVE_ARRAY = Symbol('reactivity.reactive.array');

const REACTIVE_OBJECT = Symbol('reactivity.reactive.object');

const SIGNAL = Symbol('reactivity.signal');


const STABILIZER_IDLE = 0;

const STABILIZER_RESCHEDULE = 1;

const STABILIZER_RUNNING = 2;

const STABILIZER_SCHEDULED = 3;


const STATE_NONE = 0;

const STATE_CHECK = 1 << 0;

const STATE_DIRTY = 1 << 1;

const STATE_RECOMPUTING = 1 << 2;

const STATE_IN_HEAP = 1 << 3;

const STATE_NOTIFY_MASK = (STATE_CHECK | STATE_DIRTY);


export {
    COMPILATION_TYPE_ARRAY, COMPILATION_TYPE_COMPUTED, COMPILATION_ENTRYPOINT, COMPILATION_ENTRYPOINT_REGEX, COMPILATION_NAMESPACE, COMPILATION_TYPE_SIGNAL, COMPUTED,
    PACKAGE,
    REACTIVE_ARRAY, REACTIVE_OBJECT,
    SIGNAL,
    STABILIZER_IDLE, STABILIZER_RESCHEDULE, STABILIZER_RUNNING, STABILIZER_SCHEDULED,
    STATE_CHECK, STATE_DIRTY, STATE_IN_HEAP, STATE_NONE, STATE_NOTIFY_MASK, STATE_RECOMPUTING
};
